# ==============================================================
# CONFIGURATION DE L'APPLICATION
# ==============================================================
spring.application.name=demo

# ==============================================================
# CONFIGURATION MYSQL (Connexion via le reseau Docker)
# ==============================================================
SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_qcm?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================================================
# SERVEUR ET TEMPLATES
# ==============================================================
server.port=9090
spring.thymeleaf.cache=false

# ==============================================================
# LOGGING
# ==============================================================
logging.level.org.hibernate.SQL=DEBUG